[project]
name = "database-server"
version = "0.1.0"
description = "Simple Database server for MatCreator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ase>=3.26.0",
    "mcp"
]