[project]
name = "dpa"
version = "0.1.0"
description = "Deep Potential Agent for atomistic simulation"
readme = "README.md"
requires-python = "==3.12"

dependencies = [
    "deepmd-kit==3.1.0",  
    "numpy==1.26.4",   
    "ase>=3.26.0",
    "pyyaml",
    "science-agent-sdk"
]